default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#  timeout: 5000
  username: root
  password: password
  host: 127.0.0.1

development:
  <<: *default
  database: share_kkc_development

test:
  <<: *default
  database: share_kkc_test

production:
  <<: *default
  database: share_kkc_production
