default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  host: localhost
  password:
  port: 3306

development:
  <<: *default
  database: share_kkc_development
  host: <%= ENV.fetch("DEV_DATABASE_HOST") { 'share-kkc-db' } %>
  username: <%= ENV.fetch("DEV_DATABASE_USER_NAME") { 'kkc-member' } %>
  password: <%= ENV.fetch("DEV_DATABASE_PASSWORD") { '1234_Passw0rd' } %>

test:
  <<: *default
  database: share_kkc_test

production:
  <<: *default
  database: share_kkc_production
